name: Deploy for production

on:
  pull_request:
    branches: [ main ]

jobs:
  production:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: borales/actions-yarn@v4
        name: yarn install
        with:
          cmd: install

      - uses: borales/actions-yarn@v4
        name: yarn export
        with:
          cmd: export

      - name: Pushes to the blog github pages
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'docs'
          destination-github-username: 'B-sirius'
          destination-repository-name: 'b-sirius.github.io'
          target-branch: main

      